from __future__ import annotations

CLASSIFICATIONS = [
    {
        "id": "isco08",
        "acronym": "ISCO-08",
        "name": "International Standard Classification of Occupations",
        "version": "2008",
        "custodian": "International Labour Organization",
        "domain": "labour",
        "status": "current",
        "coverage": "full_titles",
        "description": "Classifies jobs by tasks and duties. Usually used for post-interview coding from job title and task descriptions.",
        "source_url": "https://isco.ilo.org/en/isco-08/",
        "licence_note": "Complete code/title hierarchy verified against ILO ISCO-08; retrieved through an open mirror because the ILO download was unavailable. Definitions remain linked to ILO.",
    },
    {
        "id": "icse18",
        "acronym": "ICSE-18",
        "name": "International Classification of Status in Employment",
        "version": "2018",
        "custodian": "International Labour Organization",
        "domain": "labour",
        "status": "current",
        "coverage": "core",
        "description": "Classifies jobs by the type of authority and economic risk of the worker's employment relationship.",
        "source_url": "https://ilostat.ilo.org/resources/concepts-and-definitions/classification-status-at-work/",
        "licence_note": "Official ILO standard; concise categories included with attribution.",
    },
    {
        "id": "icls_lfs19",
        "acronym": "ICLS-19 LFS",
        "name": "Labour Force Status Classification",
        "version": "19th ICLS (2013)",
        "custodian": "International Labour Organization",
        "domain": "labour",
        "status": "current",
        "coverage": "core",
        "description": "Core labour-force-status categories: employed, unemployed and outside the labour force.",
        "source_url": "https://www.ilo.org/resource/overview-19th-icls-resolution-concerning-statistics-work-employment-and",
        "licence_note": "Core categories from the 19th ICLS resolution; national operational questions require the full ILO measurement framework.",
    },
    {
        "id": "icsaw18",
        "acronym": "ICSaW-18",
        "name": "International Classification of Status at Work",
        "version": "2018",
        "custodian": "International Labour Organization",
        "domain": "labour",
        "status": "current",
        "coverage": "core",
        "description": "Broader status-at-work framework covering employment and other forms of work.",
        "source_url": "https://ilostat.ilo.org/resources/concepts-and-definitions/classification-status-at-work/",
        "licence_note": "Reference metadata only pending structured official source.",
    },
    {
        "id": "isic5",
        "acronym": "ISIC Rev.5",
        "name": "International Standard Industrial Classification of All Economic Activities",
        "version": "5",
        "custodian": "United Nations Statistics Division",
        "domain": "economic activity",
        "status": "current",
        "coverage": "full",
        "description": "Classifies productive economic activities of establishments and other statistical units.",
        "source_url": "https://unstats.un.org/unsd/classifications/Econ/isic",
        "licence_note": "Official UNSD structure redistributed with attribution; verify UN terms for downstream republication.",
    },
    {
        "id": "isic4",
        "acronym": "ISIC Rev.4",
        "name": "International Standard Industrial Classification of All Economic Activities",
        "version": "4",
        "custodian": "United Nations Statistics Division",
        "domain": "economic activity",
        "status": "superseded",
        "coverage": "mapping",
        "description": "Previous ISIC version retained for validation and official correspondence to Rev.5.",
        "source_url": "https://unstats.un.org/unsd/classifications/Econ/isic",
        "licence_note": "Official correspondence data with attribution.",
    },
    {
        "id": "cpc3",
        "acronym": "CPC Ver.3.0",
        "name": "Central Product Classification",
        "version": "3.0",
        "custodian": "United Nations Statistics Division",
        "domain": "products",
        "status": "current",
        "coverage": "full",
        "description": "Classifies goods and services based on product characteristics and industrial origin.",
        "source_url": "https://unstats.un.org/unsd/classifications/Econ/CPC.cshtml",
        "licence_note": "Official UNSD structure redistributed with attribution.",
    },
    {
        "id": "coicop2018",
        "acronym": "COICOP 2018",
        "name": "Classification of Individual Consumption According to Purpose",
        "version": "2018",
        "custodian": "United Nations Statistics Division",
        "domain": "consumption",
        "status": "current",
        "coverage": "full",
        "description": "Classifies household individual consumption expenditure by purpose; central to CPI and HIES work.",
        "source_url": "https://unstats.un.org/unsd/classifications/coicop",
        "licence_note": "Official UNSD structure and explanatory text with attribution.",
    },
    {
        "id": "hs2022",
        "acronym": "HS 2022",
        "name": "Harmonized Commodity Description and Coding System",
        "version": "2022",
        "custodian": "World Customs Organization / UN Comtrade",
        "domain": "trade",
        "status": "current",
        "coverage": "full",
        "description": "International nomenclature for traded products.",
        "source_url": "https://comtradeapi.un.org/files/v1/app/reference/H6.json",
        "licence_note": "UN Comtrade reference list included; HS legal text remains subject to WCO terms.",
    },
    {
        "id": "sitc4",
        "acronym": "SITC Rev.4",
        "name": "Standard International Trade Classification",
        "version": "4",
        "custodian": "United Nations Statistics Division",
        "domain": "trade",
        "status": "current",
        "coverage": "full",
        "description": "Analytical classification of internationally traded commodities.",
        "source_url": "https://comtradeapi.un.org/files/v1/app/reference/S4.json",
        "licence_note": "UN Comtrade reference list included with attribution.",
    },
    {
        "id": "bec5",
        "acronym": "BEC Rev.5",
        "name": "Classification by Broad Economic Categories",
        "version": "5",
        "custodian": "United Nations Statistics Division",
        "domain": "trade",
        "status": "current",
        "coverage": "full",
        "description": "Groups traded products by broad end-use and SNA-oriented economic categories.",
        "source_url": "https://comtradeapi.un.org/files/v1/app/reference/B5.json",
        "licence_note": "UN Comtrade reference list included with attribution.",
    },
    {
        "id": "isced2011",
        "acronym": "ISCED 2011",
        "name": "International Standard Classification of Education",
        "version": "2011",
        "custodian": "UNESCO Institute for Statistics",
        "domain": "education",
        "status": "current",
        "coverage": "seed",
        "description": "Classifies education programmes and attainment by internationally comparable levels.",
        "source_url": "https://www.uis.unesco.org/en/methods-and-tools/isced",
        "licence_note": "Core level categories included with attribution; detailed manuals remain linked.",
    },
    {
        "id": "iscedf2013",
        "acronym": "ISCED-F 2013",
        "name": "ISCED Fields of Education and Training",
        "version": "2013",
        "custodian": "UNESCO Institute for Statistics",
        "domain": "education",
        "status": "current",
        "coverage": "detailed_titles",
        "description": "Classifies fields of education and training.",
        "source_url": "https://www.uis.unesco.org/en/methods-and-tools/isced",
        "licence_note": "Broad and narrow field structure included with attribution.",
    },
    {
        "id": "icc11",
        "acronym": "ICC 1.1",
        "name": "Indicative Crop Classification",
        "version": "1.1",
        "custodian": "Food and Agriculture Organization",
        "domain": "agriculture",
        "status": "current",
        "coverage": "full_titles",
        "description": "Crop classification designed for the World Programme for the Census of Agriculture.",
        "source_url": "https://www.fao.org/statistics/caliper/classifications/icc/en",
        "licence_note": "Complete 196-item ICC 1.1 hierarchy transcribed from the official WCA 2020 Annex 4 with FAO attribution.",
    },
    {
        "id": "icd11",
        "acronym": "ICD-11 MMS",
        "name": "International Classification of Diseases for Mortality and Morbidity Statistics",
        "version": "11",
        "custodian": "World Health Organization",
        "domain": "health",
        "status": "current",
        "coverage": "reference",
        "description": "Clinical and statistical classification for morbidity and mortality; specialist coding required.",
        "source_url": "https://icd.who.int/en",
        "licence_note": "WHO licence/API authentication applies; reference metadata only in bundled registry.",
    },
    {
        "id": "icf",
        "acronym": "ICF",
        "name": "International Classification of Functioning, Disability and Health",
        "version": "2001",
        "custodian": "World Health Organization",
        "domain": "health and disability",
        "status": "current",
        "coverage": "reference",
        "description": "Framework for describing functioning, disability and contextual factors.",
        "source_url": "https://www.who.int/standards/classifications/international-classification-of-functioning-disability-and-health",
        "licence_note": "WHO classification licensing applies; reference metadata only.",
    },
    {
        "id": "iccs1",
        "acronym": "ICCS 1.0",
        "name": "International Classification of Crime for Statistical Purposes",
        "version": "1.0",
        "custodian": "United Nations Office on Drugs and Crime",
        "domain": "crime",
        "status": "current",
        "coverage": "detailed_titles",
        "description": "Behaviour-based classification of criminal offences for administrative and survey statistics.",
        "source_url": "https://www.unodc.org/unodc/en/data-and-analysis/statistics/iccs.html",
        "licence_note": "Top-level structure included with attribution; detailed definitions remain linked.",
    },
    {
        "id": "m49",
        "acronym": "UN M49",
        "name": "Standard Country or Area Codes for Statistical Use",
        "version": "current",
        "custodian": "United Nations Statistics Division",
        "domain": "geography",
        "status": "current",
        "coverage": "full",
        "description": "Three-digit country/area codes and UN geographic groupings; national census geography is intentionally out of scope.",
        "source_url": "https://unstats.un.org/unsd/methodology/m49/",
        "licence_note": "Official UNSD M49 country/area table included; no national administrative or census codes.",
    },
    {
        "id": "sdmx",
        "acronym": "SDMX CDCL",
        "name": "SDMX Cross-Domain Code Lists",
        "version": "current",
        "custodian": "SDMX Secretariat",
        "domain": "structural metadata",
        "status": "current",
        "coverage": "seed",
        "description": "Common statistical codelists for frequency, sex, observation status, confidentiality and related concepts.",
        "source_url": "https://sdmx.org/sdmx_cdcl/",
        "licence_note": "Selected common codes included with attribution.",
    },
    {
        "id": "mics7_responses",
        "acronym": "MICS7 Response Codelists",
        "name": "MICS7 Standard Questionnaire Response Categories",
        "version": "7.1",
        "custodian": "UNICEF Multiple Indicator Cluster Surveys",
        "domain": "household surveys",
        "status": "current",
        "coverage": "curated",
        "description": "Question-specific MICS7 response categories for questionnaire comparison and design; identifiers preserve their codelist namespace.",
        "source_url": "https://classifications.impactengines.ai/provenance/mics7",
        "licence_note": "Curated operational subset with UNICEF attribution. Codes must not be assumed interchangeable across questions or MICS rounds.",
    },
    {
        "id": "icatus2016",
        "acronym": "ICATUS 2016",
        "name": "International Classification of Activities for Time-Use Statistics",
        "version": "2016",
        "custodian": "United Nations Statistics Division",
        "domain": "time use",
        "status": "current",
        "coverage": "full_titles",
        "description": "Classifies activities recorded in time-use diaries.",
        "source_url": "https://unstats.un.org/unsd/demographic-social/time-use/icatus-2016/",
        "licence_note": "Official UNSD English structure redistributed with attribution.",
    },
    {
        "id": "cofog1999",
        "acronym": "COFOG 1999",
        "name": "Classification of the Functions of Government",
        "version": "1999",
        "custodian": "United Nations Statistics Division",
        "domain": "government expenditure",
        "status": "current",
        "coverage": "full_titles",
        "description": "Classifies government expenditure by function.",
        "source_url": "https://unstats.un.org/unsd/classifications/Econ",
        "licence_note": "Official UNSD English structure redistributed with attribution.",
    },
    {
        "id": "copni1999",
        "acronym": "COPNI 1999",
        "name": "Classification of the Purposes of Non-Profit Institutions Serving Households",
        "version": "1999",
        "custodian": "United Nations Statistics Division",
        "domain": "nonprofit expenditure",
        "status": "current",
        "coverage": "full_titles",
        "description": "Classifies purposes of nonprofit institutions serving households.",
        "source_url": "https://unstats.un.org/unsd/classifications/Econ",
        "licence_note": "Official UNSD English structure redistributed with attribution.",
    },
    {
        "id": "copp1999",
        "acronym": "COPP 1999",
        "name": "Classification of the Outlays of Producers According to Purpose",
        "version": "1999",
        "custodian": "United Nations Statistics Division",
        "domain": "producer expenditure",
        "status": "current",
        "coverage": "full_titles",
        "description": "Classifies producer outlays by purpose.",
        "source_url": "https://unstats.un.org/unsd/classifications/Econ",
        "licence_note": "Official UNSD English structure redistributed with attribution.",
    },
    {
        "id": "unece_rec20",
        "acronym": "UN/CEFACT Rec.20",
        "name": "Codes for Units of Measure Used in International Trade",
        "version": "current",
        "custodian": "United Nations Economic Commission for Europe",
        "domain": "units of measure",
        "status": "current",
        "coverage": "full_titles",
        "description": "Common codes for units of measure used in administration, commerce, transport and science.",
        "source_url": "https://unece.org/trade/uncefact/cl-recommendations",
        "licence_note": "UNECE Recommendation 20 codes via the maintained Data Package mirror, with upstream attribution.",
    },
    {
        "id": "unece_rec21",
        "acronym": "UN/CEFACT Rec.21",
        "name": "Codes for Types of Cargo, Packages and Packaging Materials",
        "version": "current",
        "custodian": "United Nations Economic Commission for Europe",
        "domain": "packaging",
        "status": "current",
        "coverage": "full_titles",
        "description": "Codes for package types used in international trade.",
        "source_url": "https://unece.org/trade/uncefact/cl-recommendations",
        "licence_note": "UNECE Recommendation 21 codes via the maintained Data Package mirror, with upstream attribution.",
    },
    {
        "id": "dhs8_responses",
        "acronym": "DHS-8 Codelists",
        "name": "DHS Phase 8 Standard Questionnaire Response Categories",
        "version": "8",
        "custodian": "The DHS Program",
        "domain": "household surveys",
        "status": "current",
        "coverage": "curated",
        "description": "Selected versioned DHS-8 response codelists; analytical indicators are excluded.",
        "source_url": "https://dhsprogram.com/publications/publication-dhsq8-dhs-questionnaires-and-manuals.cfm",
        "licence_note": "Curated from DHS-8 model questionnaires; country adaptations and DHS terms must be checked.",
    },
    {
        "id": "wg_responses",
        "acronym": "WG Question Sets",
        "name": "Washington Group Functioning Response Codelists",
        "version": "current",
        "custodian": "Washington Group on Disability Statistics",
        "domain": "functioning and disability",
        "status": "current",
        "coverage": "curated",
        "description": "Response scales used by named Washington Group question sets.",
        "source_url": "https://www.washingtongroup-disability.com/question-sets/",
        "licence_note": "Question-set-specific response scales with attribution; wording and implementation guidance remain authoritative upstream.",
    },
    {
        "id": "jmp2018_responses",
        "acronym": "JMP WASH Codelists",
        "name": "WHO/UNICEF JMP WASH Categories and Service Ladders",
        "version": "2018",
        "custodian": "WHO/UNICEF Joint Monitoring Programme",
        "domain": "water sanitation and hygiene",
        "status": "current",
        "coverage": "curated",
        "description": "Survey response mappings and derived categorical service ladders; indicator estimates are excluded.",
        "source_url": "https://washdata.org/report/jmp-2018-core-questions-household-surveys",
        "licence_note": "Curated from official JMP core-question guidance with attribution.",
    },
    {
        "id": "who_vax_responses",
        "acronym": "WHO Vaccination Survey Codelists",
        "name": "WHO Vaccination Coverage Survey Response Categories",
        "version": "current",
        "custodian": "World Health Organization",
        "domain": "immunization surveys",
        "status": "current",
        "coverage": "curated",
        "description": "Evidence-source and record-availability categories for vaccination coverage surveys.",
        "source_url": "https://www.who.int/teams/immunization-vaccines-and-biologicals/immunization-analysis-and-insights/global-monitoring/immunization-coverage/survey-methods",
        "licence_note": "Curated operational categories; current WHO survey manuals remain authoritative.",
    },
    {
        "id": "fao_wca2020_responses",
        "acronym": "WCA 2020 Codelists",
        "name": "FAO World Programme for the Census of Agriculture Categories",
        "version": "2020",
        "custodian": "Food and Agriculture Organization",
        "domain": "agricultural census",
        "status": "current",
        "coverage": "curated",
        "description": "Selected land-use, livestock, holding and machinery categories used in agricultural censuses.",
        "source_url": "https://www.fao.org/world-census-agriculture/wca-round/wca-round-2020/en",
        "licence_note": "Curated discovery layer from WCA 2020 guidance; not a substitute for national adaptations or the full programme.",
    },
]

CONCEPT_RULES = {
    "mics7_responses": {
        "concept": "MICS standard questionnaire categories",
        "positive": [
            "mics",
            "multiple indicator cluster",
            "drinking water source",
            "source of drinking water",
            "piped into dwelling",
            "surface water",
            "sanitation facility",
            "birth registration",
            "child discipline",
            "child functioning",
            "vaccination card",
            "care seeking",
        ],
        "priority": [
            "birth registration",
            "child discipline",
            "child functioning",
            "vaccination",
            "drinking water",
            "water source",
            "sanitation facility",
            "school attendance",
        ],
        "negative": [
            "official number",
            "time series",
            "indicator",
            "proportion",
            "percentage",
            "prevalence",
            "rate",
            "denominator",
            "numerator",
            "estimate",
            "analysis",
        ],
        "reason": "The wording concerns a topic with standard MICS questionnaire response categories.",
        "usage_mode": "compare with the round-specific MICS codelist; customise only with documented mappings",
    },
    "icls_lfs19": {
        "concept": "labour force status",
        "positive": [
            "labour force status",
            "employed unemployed",
            "outside the labour force",
            "not in the labour force",
            "worked last week",
            "sought work",
            "looking for work",
            "available for work",
        ],
        "priority": ["labour force status", "outside the labour force", "not in the labour force"],
        "negative": ["employee", "employer", "own-account", "job title"],
        "reason": "The wording concerns whether a person is employed, unemployed or outside the labour force.",
        "usage_mode": "derive using the ILO activity, job-search and availability framework",
    },
    "icse18": {
        "concept": "status in employment",
        "positive": [
            "employee",
            "employer",
            "own account",
            "own-account",
            "self employed",
            "self-employed",
            "contributing family",
            "unpaid family",
            "relationship to employer",
            "class of worker",
            "position in employment",
        ],
        "negative": ["job title", "main tasks", "goods produced", "industry"],
        "reason": "The wording concerns the worker's employment relationship and economic risk.",
        "usage_mode": "direct answer list or derived detailed coding",
    },
    "isco08": {
        "concept": "occupation",
        "positive": ["occupation", "job title", "main tasks", "duties", "work do", "profession"],
        "negative": ["employee", "employer", "industry", "goods produced"],
        "reason": "The wording concerns the tasks and duties performed in a job.",
        "usage_mode": "post-interview coding from verbatim job title and tasks",
    },
    "isic5": {
        "concept": "industry or economic activity",
        "positive": [
            "industry",
            "economic activity",
            "workplace activity",
            "establishment",
            "goods produced",
            "goods or services",
            "mainly produce",
            "services provided",
            "business activity",
        ],
        "negative": ["job title", "education level"],
        "reason": "The wording concerns the economic activity of an establishment or enterprise.",
        "usage_mode": "post-interview coding from establishment activity descriptions",
    },
    "isced2011": {
        "concept": "level of education",
        "positive": [
            "highest education",
            "highest level of education",
            "education level",
            "grade completed",
            "qualification",
            "school level",
            "educational attainment",
        ],
        "negative": ["field of study", "subject studied"],
        "reason": "The wording concerns education programme level or attainment.",
        "usage_mode": "map national education categories to ISCED",
    },
    "iscedf2013": {
        "concept": "field of education",
        "positive": [
            "field of study",
            "field of your degree",
            "field of qualification",
            "field of education",
            "subject studied",
            "training field",
            "degree subject",
        ],
        "priority": [
            "field of study",
            "field of your degree",
            "field of qualification",
            "field of education",
            "degree subject",
        ],
        "negative": ["highest education", "grade completed"],
        "reason": "The wording concerns the subject or field studied.",
        "usage_mode": "direct broad list or post-interview detailed coding",
    },
    "coicop2018": {
        "concept": "household consumption purpose",
        "positive": [
            "household expenditure",
            "consumption",
            "item purchased",
            "spent on",
            "expenditure item",
        ],
        "negative": ["government expenditure"],
        "reason": "The wording concerns individual household consumption expenditure by purpose.",
        "usage_mode": "post-collection coding or structured expenditure item list",
    },
    "icc11": {
        "concept": "crop type",
        "positive": ["crop", "crops grown", "crop harvested", "planted crop"],
        "negative": ["occupation"],
        "reason": "The wording concerns crops grown on an agricultural holding.",
        "usage_mode": "searchable interviewer choice list",
    },
    "icd11": {
        "concept": "disease or cause of death",
        "positive": ["diagnosis", "disease", "cause of death", "health condition"],
        "negative": ["self reported symptom"],
        "reason": "The wording may concern a disease or cause-of-death classification.",
        "usage_mode": "specialist clinical or mortality coding; not a respondent choice list",
    },
    "icf": {
        "concept": "functioning and disability",
        "positive": [
            "functioning",
            "difficulty seeing",
            "difficulty hearing",
            "mobility",
            "disability",
        ],
        "negative": ["diagnosis"],
        "reason": "The wording concerns functioning rather than diagnosis.",
        "usage_mode": "measurement framework; use validated question sets where applicable",
    },
    "iccs1": {
        "concept": "crime or offence",
        "positive": ["offence", "crime", "victimisation", "criminal act"],
        "negative": ["legal statute number"],
        "reason": "The wording concerns behaviour-based crime categories.",
        "usage_mode": "administrative or post-survey coding",
    },
    "icatus2016": {
        "concept": "time-use activity",
        "positive": [
            "time use",
            "time-use",
            "activity diary",
            "how spent time",
            "unpaid care time",
        ],
        "negative": ["industry"],
        "reason": "The wording concerns activities recorded in a time-use diary.",
        "usage_mode": "code diary episodes or harmonise activity categories",
    },
    "cofog1999": {
        "concept": "government function",
        "positive": [
            "government function",
            "government expenditure",
            "public spending",
            "public expenditure",
        ],
        "negative": ["household expenditure"],
        "reason": "The wording concerns government expenditure by function.",
        "usage_mode": "administrative or public-finance coding",
    },
    "copni1999": {
        "concept": "nonprofit purpose",
        "positive": [
            "nonprofit purpose",
            "non-profit purpose",
            "ngo expenditure",
            "nonprofit expenditure",
        ],
        "negative": [],
        "reason": "The wording concerns purposes of nonprofit institutions serving households.",
        "usage_mode": "institutional expenditure coding",
    },
    "copp1999": {
        "concept": "producer outlay purpose",
        "positive": ["producer outlay", "producer expenditure", "business outlay purpose"],
        "negative": [],
        "reason": "The wording concerns producer outlays by purpose.",
        "usage_mode": "business-accounting classification",
    },
    "unece_rec20": {
        "concept": "unit of measure",
        "positive": [
            "unit of measure",
            "measurement unit",
            "kilogram",
            "litre",
            "liter",
            "hectare",
        ],
        "negative": [],
        "reason": "The wording requires a standard unit-of-measure code.",
        "usage_mode": "direct code validation or interoperable unit list",
    },
    "unece_rec21": {
        "concept": "package type",
        "positive": ["package type", "packaging type", "drum", "carton", "container type"],
        "negative": [],
        "reason": "The wording requires a standard package-type code.",
        "usage_mode": "trade or logistics coding",
    },
    "dhs8_responses": {
        "concept": "DHS standard questionnaire categories",
        "positive": [
            "dhs",
            "demographic and health survey",
            "contraceptive method",
            "place of delivery",
            "vaccination evidence",
            "vaccination card",
        ],
        "negative": ["indicator", "prevalence", "rate"],
        "reason": "The wording concerns a DHS-8 questionnaire response list.",
        "usage_mode": "consider the relevant DHS-8 codelists and verify country adaptation",
    },
    "wg_responses": {
        "concept": "Washington Group response scale",
        "positive": [
            "washington group",
            "wg short set",
            "cannot do at all",
            "functioning difficulty scale",
            "child functioning",
            "functioning difficulty",
        ],
        "negative": ["diagnosis"],
        "reason": "The wording concerns a Washington Group-aligned functioning response scale.",
        "usage_mode": "compare the relevant named WG question-set scales",
    },
    "jmp2018_responses": {
        "concept": "JMP WASH category or service ladder",
        "positive": [
            "jmp",
            "service ladder",
            "improved water",
            "unimproved sanitation",
            "open defecation",
            "hygiene facility",
            "drinking water source",
            "sanitation facility",
        ],
        "negative": ["estimate", "time series"],
        "reason": "The wording concerns JMP WASH categorical mappings rather than indicator estimates.",
        "usage_mode": "consider the relevant detailed-source mappings and service-ladder codelists",
    },
    "who_vax_responses": {
        "concept": "vaccination coverage survey category",
        "positive": [
            "who vaccination",
            "vaccination evidence",
            "home-based record",
            "vaccination record",
            "vaccination card",
            "caregiver recall",
        ],
        "negative": ["coverage estimate", "rate"],
        "reason": "The wording concerns WHO vaccination ascertainment categories.",
        "usage_mode": "consider the relevant WHO record, evidence and dose-status codelists",
    },
    "fao_wca2020_responses": {
        "concept": "agricultural census category",
        "positive": [
            "agricultural census",
            "holding sector",
            "livestock group",
            "land use class",
            "farm machinery source",
        ],
        "negative": ["crop species"],
        "reason": "The wording concerns a WCA agricultural-census codelist.",
        "usage_mode": "select one WCA codelist and document national adaptation",
    },
}

SEED_CODES = {
    "icls_lfs19": [
        ("1", "Employed"),
        ("2", "Unemployed"),
        ("3", "Outside the labour force"),
    ],
    "icse18": [
        ("1", "Employers"),
        ("11", "Employers in corporations"),
        ("12", "Employers in household market enterprises"),
        ("2", "Independent workers without employees"),
        ("21", "Owner-operators of corporations without employees"),
        ("22", "Own-account workers in household market enterprises without employees"),
        ("30", "Dependent contractors"),
        ("4", "Employees"),
        ("41", "Permanent employees"),
        ("42", "Fixed-term employees"),
        ("43", "Short-term and casual employees"),
        ("44", "Paid apprentices, trainees and interns"),
        ("51", "Contributing family workers"),
    ],
    "icsaw18": [
        ("1", "Employers"),
        ("11", "Employers in corporations"),
        ("12", "Employers in household market enterprises"),
        ("13", "Employers in own-use provision of services"),
        ("14", "Employers in own-use production of goods"),
        ("2", "Independent workers without employees"),
        ("21", "Owner-operators of corporations without employees"),
        ("22", "Own-account workers in household market enterprises without employees"),
        ("23", "Independent workers in own-use provision of services without employees"),
        ("24", "Independent workers in own-use production of goods without employees"),
        ("25", "Direct volunteers"),
        ("30", "Dependent contractors"),
        ("4", "Employees"),
        ("41", "Permanent employees"),
        ("42", "Fixed-term employees"),
        ("43", "Short-term and casual employees"),
        ("44", "Paid apprentices, trainees and interns"),
        ("5", "Contributing family workers"),
        ("51", "Contributing family workers"),
        ("52", "Family helpers in own-use provision of services"),
        ("53", "Family helpers in own-use production of goods"),
        ("60", "Unpaid trainee workers"),
        ("70", "Organization-based volunteers"),
        ("90", "Other unpaid workers"),
    ],
    "isced2011": [
        ("0", "Early childhood education"),
        ("1", "Primary education"),
        ("2", "Lower secondary education"),
        ("3", "Upper secondary education"),
        ("4", "Post-secondary non-tertiary education"),
        ("5", "Short-cycle tertiary education"),
        ("6", "Bachelor's or equivalent level"),
        ("7", "Master's or equivalent level"),
        ("8", "Doctoral or equivalent level"),
        ("9", "Not elsewhere classified"),
    ],
    "iscedf2013": [
        ("00", "Generic programmes and qualifications"),
        ("01", "Education"),
        ("02", "Arts and humanities"),
        ("03", "Social sciences, journalism and information"),
        ("04", "Business, administration and law"),
        ("05", "Natural sciences, mathematics and statistics"),
        ("06", "Information and Communication Technologies"),
        ("07", "Engineering, manufacturing and construction"),
        ("08", "Agriculture, forestry, fisheries and veterinary"),
        ("09", "Health and welfare"),
        ("10", "Services"),
    ],
    "iccs1": [
        ("01", "Acts leading to death or intending to cause death"),
        ("02", "Acts causing harm or intending to cause harm to the person"),
        ("03", "Injurious acts of a sexual nature"),
        ("04", "Acts against property involving violence or threat"),
        ("05", "Acts against property only"),
        ("06", "Acts involving controlled drugs or other psychoactive substances"),
        ("07", "Acts involving fraud, deception or corruption"),
        ("08", "Acts against public order, authority and provisions of the State"),
        ("09", "Acts against public safety and state security"),
        ("10", "Acts against the natural environment"),
        ("11", "Other criminal acts not elsewhere classified"),
    ],
    "sdmx": [
        ("FREQ:A", "Annual"),
        ("FREQ:Q", "Quarterly"),
        ("FREQ:M", "Monthly"),
        ("SEX:F", "Female"),
        ("SEX:M", "Male"),
        ("SEX:T", "Total"),
        ("OBS_STATUS:A", "Normal value"),
        ("OBS_STATUS:E", "Estimated value"),
        ("OBS_STATUS:P", "Provisional value"),
        ("CONF_STATUS:F", "Free for publication"),
        ("CONF_STATUS:C", "Confidential"),
        ("FREQ:B", "Daily-businessweek"),
        ("FREQ:D", "Daily"),
        ("FREQ:W", "Weekly"),
        ("FREQ:S", "Half-yearly"),
        ("FREQ:H", "Hourly"),
        ("UNIT_MULT:0", "Units"),
        ("UNIT_MULT:3", "Thousands"),
        ("UNIT_MULT:6", "Millions"),
        ("UNIT_MULT:9", "Billions"),
        ("DECIMALS:0", "Zero decimals"),
        ("DECIMALS:1", "One decimal"),
        ("DECIMALS:2", "Two decimals"),
        ("DECIMALS:3", "Three decimals"),
        ("TIME_FORMAT:P1Y", "Annual period"),
        ("TIME_FORMAT:P3M", "Quarterly period"),
        ("TIME_FORMAT:P1M", "Monthly period"),
    ],
}
