from __future__ import annotations

CLASSIFICATIONS = [
    {
        "id": "isco08",
        "acronym": "ISCO-08",
        "name": "International Standard Classification of Occupations",
        "version": "2008",
        "custodian": "International Labour Organization",
        "domain": "labour",
        "status": "current",
        "coverage": "full_titles",
        "description": "Classifies jobs by tasks and duties. Usually used for post-interview coding from job title and task descriptions.",
        "source_url": "https://isco.ilo.org/en/isco-08/",
        "licence_note": "Complete code/title hierarchy verified against ILO ISCO-08; retrieved through an open mirror because the ILO download was unavailable. Definitions remain linked to ILO.",
    },
    {
        "id": "icse18",
        "acronym": "ICSE-18",
        "name": "International Classification of Status in Employment",
        "version": "2018",
        "custodian": "International Labour Organization",
        "domain": "labour",
        "status": "current",
        "coverage": "seed",
        "description": "Classifies jobs by the type of authority and economic risk of the worker's employment relationship.",
        "source_url": "https://ilostat.ilo.org/resources/concepts-and-definitions/classification-status-at-work/",
        "licence_note": "Official ILO standard; concise categories included with attribution.",
    },
    {
        "id": "icsaw18",
        "acronym": "ICSaW-18",
        "name": "International Classification of Status at Work",
        "version": "2018",
        "custodian": "International Labour Organization",
        "domain": "labour",
        "status": "current",
        "coverage": "reference",
        "description": "Broader status-at-work framework covering employment and other forms of work.",
        "source_url": "https://ilostat.ilo.org/resources/concepts-and-definitions/classification-status-at-work/",
        "licence_note": "Reference metadata only pending structured official source.",
    },
    {
        "id": "isic5",
        "acronym": "ISIC Rev.5",
        "name": "International Standard Industrial Classification of All Economic Activities",
        "version": "5",
        "custodian": "United Nations Statistics Division",
        "domain": "economic activity",
        "status": "current",
        "coverage": "full",
        "description": "Classifies productive economic activities of establishments and other statistical units.",
        "source_url": "https://unstats.un.org/unsd/classifications/Econ/isic",
        "licence_note": "Official UNSD structure redistributed with attribution; verify UN terms for downstream republication.",
    },
    {
        "id": "isic4",
        "acronym": "ISIC Rev.4",
        "name": "International Standard Industrial Classification of All Economic Activities",
        "version": "4",
        "custodian": "United Nations Statistics Division",
        "domain": "economic activity",
        "status": "superseded",
        "coverage": "mapping",
        "description": "Previous ISIC version retained for validation and official correspondence to Rev.5.",
        "source_url": "https://unstats.un.org/unsd/classifications/Econ/isic",
        "licence_note": "Official correspondence data with attribution.",
    },
    {
        "id": "cpc3",
        "acronym": "CPC Ver.3.0",
        "name": "Central Product Classification",
        "version": "3.0",
        "custodian": "United Nations Statistics Division",
        "domain": "products",
        "status": "current",
        "coverage": "full",
        "description": "Classifies goods and services based on product characteristics and industrial origin.",
        "source_url": "https://unstats.un.org/unsd/classifications/Econ/CPC.cshtml",
        "licence_note": "Official UNSD structure redistributed with attribution.",
    },
    {
        "id": "coicop2018",
        "acronym": "COICOP 2018",
        "name": "Classification of Individual Consumption According to Purpose",
        "version": "2018",
        "custodian": "United Nations Statistics Division",
        "domain": "consumption",
        "status": "current",
        "coverage": "full",
        "description": "Classifies household individual consumption expenditure by purpose; central to CPI and HIES work.",
        "source_url": "https://unstats.un.org/unsd/classifications/coicop",
        "licence_note": "Official UNSD structure and explanatory text with attribution.",
    },
    {
        "id": "hs2022",
        "acronym": "HS 2022",
        "name": "Harmonized Commodity Description and Coding System",
        "version": "2022",
        "custodian": "World Customs Organization / UN Comtrade",
        "domain": "trade",
        "status": "current",
        "coverage": "full",
        "description": "International nomenclature for traded products.",
        "source_url": "https://comtradeapi.un.org/files/v1/app/reference/H6.json",
        "licence_note": "UN Comtrade reference list included; HS legal text remains subject to WCO terms.",
    },
    {
        "id": "sitc4",
        "acronym": "SITC Rev.4",
        "name": "Standard International Trade Classification",
        "version": "4",
        "custodian": "United Nations Statistics Division",
        "domain": "trade",
        "status": "current",
        "coverage": "full",
        "description": "Analytical classification of internationally traded commodities.",
        "source_url": "https://comtradeapi.un.org/files/v1/app/reference/S4.json",
        "licence_note": "UN Comtrade reference list included with attribution.",
    },
    {
        "id": "bec5",
        "acronym": "BEC Rev.5",
        "name": "Classification by Broad Economic Categories",
        "version": "5",
        "custodian": "United Nations Statistics Division",
        "domain": "trade",
        "status": "current",
        "coverage": "full",
        "description": "Groups traded products by broad end-use and SNA-oriented economic categories.",
        "source_url": "https://comtradeapi.un.org/files/v1/app/reference/B5.json",
        "licence_note": "UN Comtrade reference list included with attribution.",
    },
    {
        "id": "isced2011",
        "acronym": "ISCED 2011",
        "name": "International Standard Classification of Education",
        "version": "2011",
        "custodian": "UNESCO Institute for Statistics",
        "domain": "education",
        "status": "current",
        "coverage": "seed",
        "description": "Classifies education programmes and attainment by internationally comparable levels.",
        "source_url": "https://www.uis.unesco.org/en/methods-and-tools/isced",
        "licence_note": "Core level categories included with attribution; detailed manuals remain linked.",
    },
    {
        "id": "iscedf2013",
        "acronym": "ISCED-F 2013",
        "name": "ISCED Fields of Education and Training",
        "version": "2013",
        "custodian": "UNESCO Institute for Statistics",
        "domain": "education",
        "status": "current",
        "coverage": "seed",
        "description": "Classifies fields of education and training.",
        "source_url": "https://www.uis.unesco.org/en/methods-and-tools/isced",
        "licence_note": "Broad and narrow field structure included with attribution.",
    },
    {
        "id": "icc11",
        "acronym": "ICC 1.1",
        "name": "Indicative Crop Classification",
        "version": "1.1",
        "custodian": "Food and Agriculture Organization",
        "domain": "agriculture",
        "status": "current",
        "coverage": "reference",
        "description": "Crop classification designed for the World Programme for the Census of Agriculture.",
        "source_url": "https://www.fao.org/statistics/caliper/classifications/icc/en",
        "licence_note": "FAO Caliper is authoritative; structured ingestion pending API endpoint confirmation.",
    },
    {
        "id": "icd11",
        "acronym": "ICD-11 MMS",
        "name": "International Classification of Diseases for Mortality and Morbidity Statistics",
        "version": "11",
        "custodian": "World Health Organization",
        "domain": "health",
        "status": "current",
        "coverage": "reference",
        "description": "Clinical and statistical classification for morbidity and mortality; specialist coding required.",
        "source_url": "https://icd.who.int/en",
        "licence_note": "WHO licence/API authentication applies; reference metadata only in bundled registry.",
    },
    {
        "id": "icf",
        "acronym": "ICF",
        "name": "International Classification of Functioning, Disability and Health",
        "version": "2001",
        "custodian": "World Health Organization",
        "domain": "health and disability",
        "status": "current",
        "coverage": "reference",
        "description": "Framework for describing functioning, disability and contextual factors.",
        "source_url": "https://www.who.int/standards/classifications/international-classification-of-functioning-disability-and-health",
        "licence_note": "WHO classification licensing applies; reference metadata only.",
    },
    {
        "id": "iccs1",
        "acronym": "ICCS 1.0",
        "name": "International Classification of Crime for Statistical Purposes",
        "version": "1.0",
        "custodian": "United Nations Office on Drugs and Crime",
        "domain": "crime",
        "status": "current",
        "coverage": "seed",
        "description": "Behaviour-based classification of criminal offences for administrative and survey statistics.",
        "source_url": "https://www.unodc.org/unodc/en/data-and-analysis/statistics/iccs.html",
        "licence_note": "Top-level structure included with attribution; detailed definitions remain linked.",
    },
    {
        "id": "m49",
        "acronym": "UN M49",
        "name": "Standard Country or Area Codes for Statistical Use",
        "version": "current",
        "custodian": "United Nations Statistics Division",
        "domain": "geography",
        "status": "current",
        "coverage": "full",
        "description": "Three-digit country/area codes and UN geographic groupings; national census geography is intentionally out of scope.",
        "source_url": "https://unstats.un.org/unsd/methodology/m49/",
        "licence_note": "Official UNSD M49 country/area table included; no national administrative or census codes.",
    },
    {
        "id": "sdmx",
        "acronym": "SDMX CDCL",
        "name": "SDMX Cross-Domain Code Lists",
        "version": "current",
        "custodian": "SDMX Secretariat",
        "domain": "structural metadata",
        "status": "current",
        "coverage": "seed",
        "description": "Common statistical codelists for frequency, sex, observation status, confidentiality and related concepts.",
        "source_url": "https://sdmx.org/sdmx_cdcl/",
        "licence_note": "Selected common codes included with attribution.",
    },
]

CONCEPT_RULES = {
    "icse18": {
        "concept": "status in employment",
        "positive": [
            "employee",
            "employer",
            "own account",
            "own-account",
            "self employed",
            "self-employed",
            "contributing family",
            "unpaid family",
            "relationship to employer",
            "class of worker",
            "position in employment",
        ],
        "negative": ["job title", "main tasks", "goods produced", "industry"],
        "reason": "The wording concerns the worker's employment relationship and economic risk.",
        "usage_mode": "direct answer list or derived detailed coding",
    },
    "isco08": {
        "concept": "occupation",
        "positive": ["occupation", "job title", "main tasks", "duties", "work do", "profession"],
        "negative": ["employee", "employer", "industry", "goods produced"],
        "reason": "The wording concerns the tasks and duties performed in a job.",
        "usage_mode": "post-interview coding from verbatim job title and tasks",
    },
    "isic5": {
        "concept": "industry or economic activity",
        "positive": [
            "industry",
            "economic activity",
            "workplace activity",
            "establishment",
            "goods produced",
            "goods or services",
            "mainly produce",
            "services provided",
            "business activity",
        ],
        "negative": ["job title", "education level"],
        "reason": "The wording concerns the economic activity of an establishment or enterprise.",
        "usage_mode": "post-interview coding from establishment activity descriptions",
    },
    "isced2011": {
        "concept": "level of education",
        "positive": [
            "highest education",
            "highest level of education",
            "education level",
            "grade completed",
            "qualification",
            "school level",
            "educational attainment",
        ],
        "negative": ["field of study", "subject studied"],
        "reason": "The wording concerns education programme level or attainment.",
        "usage_mode": "map national education categories to ISCED",
    },
    "iscedf2013": {
        "concept": "field of education",
        "positive": ["field of study", "subject studied", "training field", "degree subject"],
        "negative": ["highest education", "grade completed"],
        "reason": "The wording concerns the subject or field studied.",
        "usage_mode": "direct broad list or post-interview detailed coding",
    },
    "coicop2018": {
        "concept": "household consumption purpose",
        "positive": [
            "household expenditure",
            "consumption",
            "item purchased",
            "spent on",
            "expenditure item",
        ],
        "negative": ["government expenditure"],
        "reason": "The wording concerns individual household consumption expenditure by purpose.",
        "usage_mode": "post-collection coding or structured expenditure item list",
    },
    "icc11": {
        "concept": "crop type",
        "positive": ["crop", "crops grown", "crop harvested", "planted crop"],
        "negative": ["occupation"],
        "reason": "The wording concerns crops grown on an agricultural holding.",
        "usage_mode": "searchable interviewer choice list",
    },
    "icd11": {
        "concept": "disease or cause of death",
        "positive": ["diagnosis", "disease", "cause of death", "health condition"],
        "negative": ["self reported symptom"],
        "reason": "The wording may concern a disease or cause-of-death classification.",
        "usage_mode": "specialist clinical or mortality coding; not a respondent choice list",
    },
    "icf": {
        "concept": "functioning and disability",
        "positive": [
            "functioning",
            "difficulty seeing",
            "difficulty hearing",
            "mobility",
            "disability",
        ],
        "negative": ["diagnosis"],
        "reason": "The wording concerns functioning rather than diagnosis.",
        "usage_mode": "measurement framework; use validated question sets where applicable",
    },
    "iccs1": {
        "concept": "crime or offence",
        "positive": ["offence", "crime", "victimisation", "criminal act"],
        "negative": ["legal statute number"],
        "reason": "The wording concerns behaviour-based crime categories.",
        "usage_mode": "administrative or post-survey coding",
    },
}

SEED_CODES = {
    "icse18": [
        ("1", "Independent workers"),
        ("11", "Employers"),
        ("12", "Independent workers without employees"),
        ("2", "Dependent workers"),
        ("21", "Dependent contractors"),
        ("22", "Employees"),
        ("3", "Contributing family workers"),
    ],
    "isced2011": [
        ("0", "Early childhood education"),
        ("1", "Primary education"),
        ("2", "Lower secondary education"),
        ("3", "Upper secondary education"),
        ("4", "Post-secondary non-tertiary education"),
        ("5", "Short-cycle tertiary education"),
        ("6", "Bachelor's or equivalent level"),
        ("7", "Master's or equivalent level"),
        ("8", "Doctoral or equivalent level"),
        ("9", "Not elsewhere classified"),
    ],
    "iscedf2013": [
        ("00", "Generic programmes and qualifications"),
        ("01", "Education"),
        ("02", "Arts and humanities"),
        ("03", "Social sciences, journalism and information"),
        ("04", "Business, administration and law"),
        ("05", "Natural sciences, mathematics and statistics"),
        ("06", "Information and Communication Technologies"),
        ("07", "Engineering, manufacturing and construction"),
        ("08", "Agriculture, forestry, fisheries and veterinary"),
        ("09", "Health and welfare"),
        ("10", "Services"),
    ],
    "iccs1": [
        ("01", "Acts leading to death or intending to cause death"),
        ("02", "Acts causing harm or intending to cause harm to the person"),
        ("03", "Injurious acts of a sexual nature"),
        ("04", "Acts against property involving violence or threat"),
        ("05", "Acts against property only"),
        ("06", "Acts involving controlled drugs or other psychoactive substances"),
        ("07", "Acts involving fraud, deception or corruption"),
        ("08", "Acts against public order, authority and provisions of the State"),
        ("09", "Acts against public safety and state security"),
        ("10", "Acts against the natural environment"),
        ("11", "Other criminal acts not elsewhere classified"),
    ],
    "sdmx": [
        ("FREQ:A", "Annual"),
        ("FREQ:Q", "Quarterly"),
        ("FREQ:M", "Monthly"),
        ("SEX:F", "Female"),
        ("SEX:M", "Male"),
        ("SEX:T", "Total"),
        ("OBS_STATUS:A", "Normal value"),
        ("OBS_STATUS:E", "Estimated value"),
        ("OBS_STATUS:P", "Provisional value"),
        ("CONF_STATUS:F", "Free for publication"),
        ("CONF_STATUS:C", "Confidential"),
    ],
}
